apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
type: Opaque
data:
  RABBITMQ_ERLANG_COOKIE: a3JvbGlr
  RABBITMQ_DEFAULT_USER: sensu
  RABBITMQ_DEFAULT_PASS: sensu
  RABBITMQ_DEFAULT_VHOST: /sensu
