apiVersion: v1
kind: Service
metadata:
  name: sensu
spec:
  type: LoadBalancer
  ports:
    - name: uchiwa
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: api
      port: 4567
      protocol: TCP
      targetPort: 4567
  selector:
    app: sensu
